//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace CRUD_Persona.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class Perfil
    {
        public int Id_perfil { get; set; }
        public string Perfil1 { get; set; }
        public System.DateTime Vigencia { get; set; }
    }
}
