//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace CRUD_Persona.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class Usuario_Sistema
    {
        public int Id_Usuario { get; set; }
        public string Nombre { get; set; }
        public int id_depto { get; set; }
        public int id_perfil { get; set; }
        public System.DateTime fecha_vigencia { get; set; }
    }
}
